import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { agenticWorkflowDecisionFixture, decisionWorkspaceFixture, publicSectorDecisionFixture } from './consequential-decision-workspace.mjs';
import { criticalConditions, decisionState, validateDelegation } from './consequential-decision-model.mjs';

test('Decision Workspace fixture preserves unresolved alternatives and the human decision right',()=>{const d=decisionWorkspaceFixture();assert.equal(d.judgmentMode,'COLLABORATIVE_JUDGMENT');assert.equal(d.alternatives.filter(a=>a.comparisonStatus==='NONDOMINATED').length,2);assert.match(d.judgmentAssessments[0].humanDecisionRight,/bank decision authorities/);});
test('ESA acceptance fixture preserves nondominance and unsupported stability without a forced selection',()=>{const d=decisionWorkspaceFixture();assert.equal(decisionState(d).state,'COMPARISON_UNDETERMINED');assert.equal(d.alternatives.filter(a=>a.comparisonStatus==='NONDOMINATED').length,2);assert.ok(criticalConditions(d).some(item=>item.type==='SCALE_STABILITY'&&item.dimension==='stabilityViability'));});
test('FPA acceptance fixture makes institutional dependencies and an implementation authority break explicit',()=>{const d=publicSectorDecisionFixture();assert.ok(d.authorityRecords.some(a=>a.authorityType==='INSTITUTIONAL'&&a.status==='CONFIRMED'));assert.ok(d.authorityRecords.some(a=>a.authorityType==='IMPLEMENTATION'&&a.status==='DISPUTED'));assert.ok(d.alternatives[0].dependencyEffects.includes('Land-access agreements'));});
test('agentic workflow fixture retains collaborative judgment, reserved authority, and accountable delegation',()=>{const d=agenticWorkflowDecisionFixture();assert.equal(d.judgmentMode,'COLLABORATIVE_JUDGMENT');assert.ok(d.judgmentAssessments.some(a=>a.judgmentMode==='RESERVED_HUMAN_JUDGMENT'));assert.equal(validateDelegation(d.delegationRecords[0],d.authorityRecords).valid,true);});
test('Decision Workspace UI exposes the core decision surfaces without persistence-specific queries',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8'),app=await readFile(new URL('./app.js',import.meta.url),'utf8');for(const text of ['Governing question','Authority','Alternatives','Collaborative judgment','Scalability &amp; stability','least-regret next move'])assert.ok(html.toLowerCase().includes(text.toLowerCase()),text);assert.match(html,/id="consequential"/);assert.match(app,/renderDecisionWorkspace/);assert.doesNotMatch(app,/MATCH\s*\(/);assert.doesNotMatch(app,/qdrant/i);});
