import assert from 'node:assert/strict';
import test from 'node:test';
import { federationEconomics, federationStability, gateReadiness, healthcareFixture, normalizeWorkspace, reportPayload } from './feoa-workspace.mjs';

test('FEOA-A01/A02 canonical workspace persists every workflow surface',()=>{const w=healthcareFixture({opportunity:{id:'OPP-REFERRAL'}});const reloaded=normalizeWorkspace(JSON.parse(JSON.stringify(w)),{opportunity:{id:'OPP-REFERRAL'}});for(const key of ['participants','capabilities','valueStreams','processSteps','handoffs','actions','constraints','metrics','frictions','counterfactuals','economicFlows','readinessGaps','gates','aiCases','cognitiveResilience','sensitivities','pilotMeasurements'])assert.ok(reloaded[key].length>0,key);assert.equal(reloaded.assessment.opportunityId,'OPP-REFERRAL');});
test('FEOA-A03 IDs are stable and evidence is shared without duplication after reload',()=>{const w=healthcareFixture();const e=w.evidence[0];assert.match(e.id,/^EVD-/);assert.equal(w.handoffs[0].evidenceIds[0],e.id);assert.equal(w.metrics[0].evidenceIds[0],e.id);const r=normalizeWorkspace(JSON.parse(JSON.stringify(w)));assert.equal(r.evidence[0].id,e.id);assert.equal(r.evidence.length,1);});
test('FEOA-A05 handoff, action, and first-class constraint retain complete traceable relationships',()=>{const w=healthcareFixture();const h=w.handoffs[0],a=w.actions[0],c=w.constraints[0];assert.deepEqual([h.communicationState,h.responsibilityState,h.authorityState],['Acknowledged','Accepted','Pending']);assert.equal(h.actionIds[0],a.id);assert.equal(h.constraintIds[0],c.id);assert.equal(a.residualAccountableOrganization,'Primary Care Group');assert.equal(c.type,'Hard');});
test('FEOA-A04 gate lifecycle blocks readiness until each mandatory evidence condition is satisfied',()=>{const w=healthcareFixture();const g=gateReadiness(w.gates[0],w.evidence);assert.equal(g.status,'Blocked by Gaps');assert.equal(g.canBeDecisionReady,false);assert.equal(g.unmetConditions.length,1);});
test('FEOA-A06/A07 economics eliminate transfers and still flag indispensable participant misalignment',()=>{const w=healthcareFixture();const c1=w.counterfactuals.find(c=>c.id==='CASE-1');const e=federationEconomics(w,c1.id);assert.equal(e.gross,110000);assert.equal(e.transferElimination,30000);assert.equal(e.riskAdjusted,90000);assert.equal(federationStability(w).stable,false);});
test('FEOA-A08 readiness, A09 AI, A10 resilience, A11 pilot, and A12 reports persist in healthcare workflow',()=>{const w=healthcareFixture();assert.equal(w.readinessGaps[0].dimension,'Integration');assert.equal(w.aiCases[0].case1Id,'CASE-1');assert.equal(w.aiCases[0].case2Id,'CASE-2');assert.equal(w.cognitiveResilience[0].history[0].type,'Withdrawal');assert.equal(w.pilotMeasurements[0].observations[0].value,15);const report=reportPayload(w,'FEOA Executive Decision Report');assert.equal(report.assessmentId,w.assessment.id);assert.equal(report.evidence[0].id,w.evidence[0].id);});
