export const MORTGAGE_FIXTURE = Object.freeze({
  fixtureId: 'MTG-NORTH-STAR-V0.1',
  sourceArtifact: 'North Star Mortgage Demonstrator - Synthetic Data Fixture v0.1.xlsx',
  sourceSha256: 'cfecf9331396c9b86ae0f7c8d4de4c7c501d9e2b0d259df6fb7285e057968776',
  importedSheets: ['Case Inputs', 'Fictional Policy', 'Evidence Inventory', 'ERIR Source Seed'],
  excludedSheets: ['Protected Audit', 'Source Assessment', 'Calculations', 'Test Cases', 'Acceptance Criteria', 'Decision Log', 'Data Dictionary', 'README'],
  synthetic: true,
  decisionState: 'INSUFFICIENT EVIDENCE TO DECIDE',
  capability: {
    id: 'MERCA-V0.1',
    name: 'Mortgage Evidence Readiness and Consistency Assistant',
    reviewedConfigurationId: 'CFG-MERCA-001',
    currentConfigurationId: 'CFG-MERCA-001',
    operatingContext: 'Read-only synthetic community-bank mortgage demonstrator',
    permittedPurposes: ['Calculate deterministic metrics', 'Trace inputs and policy comparisons', 'Flag missing, stale, or inconsistent evidence', 'Draft questions for qualified review', 'Abstain'],
    prohibitedActions: ['Approve', 'Deny', 'Price', 'Counteroffer', 'Determine eligibility', 'Waive policy', 'Send notices', 'Write consequential records', 'Make legal or compliance conclusions']
  },
  caseInputs: [
    {id:'IN-001', field:'application_id', value:'APP-MTG-001', type:'text', visibility:'Underwriting'},
    {id:'IN-002', field:'bank', value:'Riverbend Community Bank', type:'text', visibility:'Underwriting'},
    {id:'IN-003', field:'applicant_name', value:'Maya Reed', type:'text', visibility:'Underwriting'},
    {id:'IN-005', field:'first_time_homebuyer', value:true, type:'boolean', visibility:'Underwriting'},
    {id:'IN-006', field:'employment_type', value:'W-2 employee', type:'text', visibility:'Underwriting'},
    {id:'IN-007', field:'verified_base_annual_income', value:86000, type:'currency', visibility:'Underwriting'},
    {id:'IN-008', field:'candidate_overtime_annual_income', value:8000, type:'currency', visibility:'Underwriting'},
    {id:'IN-009', field:'gross_annual_income', value:94000, type:'currency', visibility:'Underwriting'},
    {id:'IN-010', field:'credit_score', value:725, type:'integer', visibility:'Underwriting'},
    {id:'IN-011', field:'purchase_price', value:310000, type:'currency', visibility:'Underwriting'},
    {id:'IN-012', field:'loan_amount', value:292000, type:'currency', visibility:'Underwriting'},
    {id:'IN-013', field:'housing_expense_monthly', value:2460, type:'currency', visibility:'Underwriting'},
    {id:'IN-014', field:'other_debt_monthly', value:1040, type:'currency', visibility:'Underwriting'},
    {id:'IN-015', field:'liquid_reserves', value:3800, type:'currency', visibility:'Underwriting'},
    {id:'IN-016', field:'illustrative_interest_rate', value:0.065, type:'percentage', visibility:'Underwriting'},
    {id:'IN-017', field:'loan_term_months', value:360, type:'integer', visibility:'Underwriting'},
    {id:'IN-018', field:'occupancy', value:'Owner occupied', type:'text', visibility:'Underwriting'},
    {id:'IN-019', field:'product_type', value:'Conventional portfolio fixed-rate', type:'text', visibility:'Underwriting'},
    {id:'IN-020', field:'overtime_evidence_accepted', value:false, type:'boolean', visibility:'Underwriting'},
    {id:'IN-021', field:'current_asset_statement_accepted', value:false, type:'boolean', visibility:'Underwriting'},
    {id:'IN-022', field:'synthetic_marker', value:true, type:'boolean', visibility:'All'}
  ],
  policy: [
    {id:'POL-001', criterion:'credit_score', operator:'minimum', standard:700, exceptionBoundary:null, unit:'integer'},
    {id:'POL-002', criterion:'combined_ltv', operator:'maximum', standard:0.95, exceptionBoundary:null, unit:'percentage'},
    {id:'POL-003', criterion:'total_dti', operator:'maximum', standard:0.43, exceptionBoundary:0.45, unit:'percentage'},
    {id:'POL-004', criterion:'post_closing_reserves', operator:'minimum', standard:2, exceptionBoundary:1.5, unit:'months'},
    {id:'POL-005', criterion:'variable_income_evidence', operator:'accepted', standard:true, exceptionBoundary:null, unit:'boolean'},
    {id:'POL-006', criterion:'current_asset_statement', operator:'accepted', standard:true, exceptionBoundary:null, unit:'boolean'}
  ],
  evidence: [
    {id:'DOC-MTG-001', documentType:'Uniform residential application', asOf:'2026-08-10', status:'Accepted', source:'Applicant submission', usedFor:'Application identity and requested terms'},
    {id:'DOC-MTG-002', documentType:'Pay statements', asOf:'2026-08-15', status:'Accepted', source:'Employer payroll', usedFor:'Base income'},
    {id:'DOC-MTG-003', documentType:'W-2 forms', asOf:'2025-12-31', status:'Accepted', source:'Applicant/employer', usedFor:'Income history'},
    {id:'DOC-MTG-004', documentType:'Overtime continuity verification', asOf:'2026-08-20', status:'Pending', source:'Employer verification', usedFor:'Candidate overtime income'},
    {id:'DOC-MTG-005', documentType:'Credit report', asOf:'2026-08-18', status:'Accepted', source:'Fictional credit bureau', usedFor:'Credit score and liabilities'},
    {id:'DOC-MTG-006', documentType:'Purchase agreement', asOf:'2026-08-12', status:'Accepted', source:'Applicant/seller', usedFor:'Purchase price'},
    {id:'DOC-MTG-007', documentType:'Asset statement 1', asOf:'2026-07-31', status:'Accepted', source:'Fictional depository', usedFor:'Funds and reserves'},
    {id:'DOC-MTG-008', documentType:'Current asset statement 2', asOf:'2026-08-20', status:'Missing', source:'Fictional depository', usedFor:'Funds and reserves'},
    {id:'DOC-MTG-009', documentType:'Appraisal/value evidence', asOf:'2026-08-19', status:'Accepted', source:'Fictional appraiser', usedFor:'Property value'}
  ],
  erirSources: [
    {id:'ERIR-MTG-001', source:'Equal Credit Opportunity Act / Regulation B', instrumentType:'Enacted statute and regulation', status:'Current source; applicability review required', url:'https://www.consumerfinance.gov/rules-policy/regulations/1002/'},
    {id:'ERIR-MTG-002', source:'12 CFR 1002.6', instrumentType:'Enacted regulation with interpretation', status:'Current source; applicability review required', url:'https://www.consumerfinance.gov/rules-policy/regulations/1002/6/'},
    {id:'ERIR-MTG-003', source:'12 CFR 1002.9', instrumentType:'Enacted regulation with interpretation', status:'Current source; applicability review required', url:'https://www.consumerfinance.gov/rules-policy/regulations/1002/9/'},
    {id:'ERIR-MTG-004', source:'12 CFR 1002.12', instrumentType:'Enacted regulation with interpretation', status:'Current source; applicability review required', url:'https://www.consumerfinance.gov/rules-policy/regulations/1002/12/'},
    {id:'ERIR-MTG-005', source:'Fair Housing Act, 42 USC 3605', instrumentType:'Enacted statute', status:'Current source; applicability review required', url:'https://uscode.house.gov/view.xhtml?req=(title:42%20section:3605%20edition:prelim)'},
    {id:'ERIR-MTG-006', source:'HMDA / Regulation C, 12 CFR 1003.4', instrumentType:'Enacted regulation with interpretation', status:'Current source; applicability review required', url:'https://www.consumerfinance.gov/rules-policy/regulations/1003/4/'},
    {id:'ERIR-MTG-007', source:'CFPB Circular 2022-03', instrumentType:'Agency interpretive guidance', status:'Current-status check required at use', url:'https://www.consumerfinance.gov/compliance/circulars/circular-2022-03-adverse-action-notification-requirements-in-connection-with-credit-decisions-based-on-complex-algorithms/'},
    {id:'ERIR-MTG-008', source:'Revised Interagency Model Risk Management Guidance', instrumentType:'Supervisory guidance', status:'Issued 2026-04-17; applicability review required', url:'https://www.fdic.gov/news/financial-institution-letters/2026/agencies-revise-interagency-model-risk-management-guidance'},
    {id:'ERIR-MTG-009', source:'Third-Party Risk Management: A Guide for Community Banks', instrumentType:'Supervisory resource', status:'Issued 2024-05-03', url:'https://www.fdic.gov/news/financial-institution-letters/2024/third-party-risk-management-guide-community-banks'},
    {id:'ERIR-MTG-010', source:'NIST AI RMF 1.0', instrumentType:'Voluntary framework', status:'Nonbinding', url:'https://www.nist.gov/itl/ai-risk-management-framework'},
    {id:'ERIR-MTG-GAP-01', source:'FCRA adverse-action requirements', instrumentType:'Potentially applicable statute', status:'Applicability unresolved', url:'https://uscode.house.gov/view.xhtml?req=(title:15%20section:1681m%20edition:prelim)'},
    {id:'ERIR-MTG-GAP-02', source:'State mortgage, property, privacy, and anti-discrimination law', instrumentType:'Evidence gap', status:'Unresolved by design', url:''}
  ]
});
