import test from 'node:test';import assert from 'node:assert/strict';
import {PROVIDERS,canonicalStrategy,normalizeProviderRecommendation,importRecommendationJson,importAzureCsv,azureDependencyEvidence,importGcpCsv,gcpDependencyEvidence,providerCandidateAlternative,providerCoexistenceSummary} from './multicloud-modernization-adapter.mjs';

test('Azure and GCP share canonical strategy mapping',()=>{assert.equal(canonicalStrategy('Replatform'),'replatform');assert.equal(canonicalStrategy('Re-architect'),'refactor')});
test('missing provider confidence remains null',()=>{const r=normalizeProviderRecommendation({applicationId:'A',strategy:'Rehost'},{provider:PROVIDERS.AZURE});assert.equal(r.confidence,null);assert.equal(r.status,'Advisory evidence only')});
test('Azure recommendation JSON remains advisory',()=>{const r=importRecommendationJson([{applicationId:'A',strategy:'Replatform',targetDestination:'Azure App Service'}],{provider:PROVIDERS.AZURE,sourceSystem:'Azure Migrate'});assert.equal(r.recommendations[0].provider,PROVIDERS.AZURE);assert.equal(r.recommendations[0].canonicalStrategy,'replatform')});
test('GCP recommendation JSON remains advisory',()=>{const r=importRecommendationJson([{applicationId:'A',strategy:'Rehost',targetDestination:'Compute Engine'}],{provider:PROVIDERS.GCP,sourceSystem:'Migration Center'});assert.equal(r.recommendations[0].provider,PROVIDERS.GCP);assert.equal(r.recommendations[0].canonicalStrategy,'rehost')});
test('Azure dependency export preserves documented fields',()=>{const imp=importAzureCsv('Timeslot,Source server name,Source application,Source process,Destination server name,Destination IP,Destination application,Destination process,Destination port\nT1,S1,App1,p1,S2,10.0.0.2,App2,p2,443\n',{exportType:'Dependency export'});const d=azureDependencyEvidence(imp)[0];assert.equal(d.sourceServer,'S1');assert.equal(d.destinationPort,'443')});
test('GCP network dependencies remain provider evidence',()=>{const imp=importGcpCsv('Source IP,Destination IP,Port,Protocol,Service\n10.0.0.1,10.0.0.2,443,tcp,https\n',{reportType:'Network dependencies'});const d=gcpDependencyEvidence(imp)[0];assert.equal(d.port,'443');assert.match(d.status,/mapping requires review/)});
test('provider candidate does not become selected decision',()=>{const alt=providerCandidateAlternative({id:'R',provider:PROVIDERS.GCP,applicationId:'A',strategy:'Replatform',targetDestination:'Cloud Run',confidence:.7});assert.equal(alt.decisionStatus,'Candidate / provider evidence');assert.equal(alt.provider,PROVIDERS.GCP)});
test('AWS Azure GCP can coexist without ranking',()=>{const s=providerCoexistenceSummary([{provider:'AWS'},{provider:PROVIDERS.AZURE},{provider:PROVIDERS.GCP}]);assert.equal(s.providers.length,3);assert.equal(s.multiProvider,true);assert.match(s.authorityState,/no provider is selected/i)});
