import assert from 'node:assert/strict';
import test from 'node:test';
import { classifyEconomicAttribution, evaluateRequiredMemberViability, rankFormAlternatives, scenarioComparison, validateDistributionRules } from './federated-fofa-mcvsm-model.mjs';
import { normalizeEvidenceLineage, normalizePermission, validateAsOfReconstruction, validateCommitmentState, validateDependencyMembershipSeparation, validateExecutionAgainstCommitment } from './federated-facem-model.mjs';
import { evaluateAbstention, evaluateBoundedRelease, evaluateRecoveryCase, deriveAICapabilityLifecycleState, validateAIOutputBoundary, validateAISuspension } from './federated-bacrm-model.mjs';
import { normalizeWorkspace } from './feoa-workspace.mjs';

const synthetic = 'Synthetic / modeled';
const members = ['PAR-MERIDIAN', 'PAR-APEX', 'PAR-HARBOR'];
const authority = { id: 'AE-COORD', effectiveDate: '2027-01-01', status: 'Active', actions: [], relationships: [], evidenceRequirements: [], decisionHistory: [] };
const permission = { id: 'PER-COORD', grantorSubjectId: 'MORGAN', holderParticipantId: 'PAR-HARBOR', purpose: 'Referral/service coordination', effectiveFrom: '2027-01-01T00:00:00Z', createsAuthority: false };
const capability = { id: 'CAP-RANK-001', version: '1.0-synthetic', purpose: 'Rank already-eligible staffing/service-coordination options for accountable human review', sponsorMemberId: 'PAR-HARBOR', permittedFunctions: ['Filter approved constraints', 'Rank eligible options', 'Display reasons, uncertainty, and missing-data flags'], prohibitedFunctions: ['Diagnosis', 'Eligibility/referral decision', 'Staff assignment', 'Scheduling', 'Messaging/commitment', 'Legal/compliance decision', 'Autonomous record update except audit logging'], status: synthetic };
const baseline = { id: 'BASE-RANK', aiCapabilityId: capability.id, workIds: ['WORK-COORDINATION'], processDefinition: 'Manual review of eligible staffing/service-coordination options', accountableOwnerId: 'PAR-HARBOR', requiredRoleIds: ['ROLE-COORDINATOR'], inputDefinition: 'Approved eligible option records', outputDefinition: 'Human-review queue', testResult: 'Synthetic process test passed', fallbackEligible: true, status: synthetic };
const fallback = { id: 'FB-RANK', nonAIBaselineId: baseline.id, ownerId: 'PAR-HARBOR', stepIds: ['STEP-MANUAL-QUEUE'], capacityEvidenceIds: ['EVD-CAPACITY'], maximumDuration: '8 hours', escalationRule: 'Escalate to accountable operations owner', status: synthetic };
const input = { id: 'IN-RANK', aiCapabilityId: capability.id, dataElement: 'Eligible option attributes', sourceParticipantId: 'PAR-HARBOR', sourceSystemId: 'SYS-OPTIONS', purposeNecessity: 'Rank already eligible options', provenanceRequirement: 'Source version required', permissionId: permission.id, qualityRule: 'Approved constraint completeness', identityConfidenceRule: 'Verified participant identity', prohibitedInference: 'No clinical, legal, or eligibility inference', trainingUseAllowed: false, secondaryUseAllowed: false, retentionRule: 'Case-bound', missingInvalidResponse: 'ABSTAIN and use FBP-RANK', status: synthetic };
const output = { id: 'OUT-RANK', aiCapabilityId: capability.id, outputType: 'Ranked eligible options', recipientRoleId: 'ROLE-COORDINATOR', meaning: 'Review proposal only', uncertaintyDisplay: 'Reasons and missing-data flags', permittedDownstreamUse: 'Accountable human review only', prohibitedUse: 'No assignment, scheduling, messaging, commitment, authority, completion, diagnosis, or legal decision', reviewRequired: true, decisionOwnerId: 'PAR-HARBOR', authorityId: authority.id, permittedHumanAction: 'Review and separately decide', reversibility: 'Reversible before any separate action', status: synthetic };
const crosswalk = { id: 'ACW-RANK', outputBoundaryId: output.id, proposedAction: 'Review ranked options', aiRole: 'ranking assistant', humanRoleId: 'ROLE-COORDINATOR', decisionOwnerId: 'PAR-HARBOR', authorityId: authority.id, permissionId: permission.id, commitmentId: 'COM-COORD', effectiveTimeCheckRequired: true, permitted: true, preconditions: ['Approved input boundary'], status: synthetic };
const releaseDecision = { id: 'RLD-RANK', aiCapabilityId: capability.id, version: capability.version, disposition: 'RELEASED_BOUNDED', intendedUseBoundary: 'Review only', decisionOwnerId: 'PAR-HARBOR', authorityId: authority.id, effectiveTime: '2027-01-15T00:00:00Z', status: synthetic };

test('North Star integrated execution traverses FOFA, MCVSM, FACEM, BACRM, and C3 loopback without semantic collapse', () => {
  const formScores = [['FORM-INDEPENDENCE', 2.3375], ['FORM-BILATERAL', 2.7625], ['FORM-NETWORK', 2.9495], ['FORM-JV', 2.941], ['FORM-ACQUISITION', 3.0855], ['FORM-FEDERATION', 3.57]];
  const criteria = [{ id: 'CR-SYNTHETIC', name: 'Evidence-adjusted architectural suitability', definition: 'Synthetic process-test criterion', weight: 1, critical: false, status: synthetic }];
  const alternatives = formScores.map(([id], index) => ({ id, formType: id, operatingDescription: 'Synthetic alternative', status: synthetic, bestNonFederation: index === 2 }));
  const ratings = formScores.map(([alternativeId, rating]) => ({ id: `R-${alternativeId}`, alternativeId, criterionId: 'CR-SYNTHETIC', rating, confidence: 'Synthetic / modeled' }));
  const fofA = rankFormAlternatives(alternatives, criteria, ratings);
  assert.equal(fofA.ranking[0].alternativeId, 'FORM-FEDERATION'); assert.equal(fofA.decision, null); assert.equal(fofA.selectsForm, false);

  const economicCases = { C2: { collectiveNPV: 770525.48, collectiveROI: 0.711439, benefitCostRatio: 1.7114, memberNPVs: [105433.38, 107081.95, 558010.14] }, C3: { collectiveNPV: 193580.99, collectiveROI: 0.332593, benefitCostRatio: 1.3326, memberNPVs: [46214.86, 35227.56, 112138.57] } };
  const workspace = normalizeWorkspace({ participants: members.map(id => ({ id, required: true, status: synthetic })), counterfactuals: [{ id: 'C0', caseType: 'CURRENT_INDEPENDENT', status: synthetic }, { id: 'C1', caseType: 'BEST_NON_FEDERATION', status: synthetic }, { id: 'C2', caseType: 'FEDERATION_NON_AI', comparatorCaseId: 'C1', status: synthetic }, { id: 'C3', caseType: 'FEDERATION_BOUNDED_AI', comparatorCaseId: 'C2', aiCapabilityId: capability.id, status: synthetic }], economicFlows: [{ id: 'C1-B', caseId: 'C1', type: 'External Revenue', direction: 'Inflow', amount: 0, status: synthetic }, { id: 'C2-B', caseId: 'C2', type: 'External Revenue', direction: 'Inflow', amount: 439200, status: synthetic }, { id: 'C2-C', caseId: 'C2', type: 'External Cost', direction: 'Outflow', amount: 120000, status: synthetic }, { id: 'C2-R', caseId: 'C2', type: 'External Cost', direction: 'Outflow', amount: 30000, status: synthetic }, { id: 'C3-B', caseId: 'C3', type: 'External Revenue', direction: 'Inflow', amount: 622980, status: synthetic }, { id: 'C3-C', caseId: 'C3', type: 'External Cost', direction: 'Outflow', amount: 200000, status: synthetic }, { id: 'C3-R', caseId: 'C3', type: 'External Cost', direction: 'Outflow', amount: 50000, status: synthetic }], memberEconomicThresholds: members.flatMap((participantId, index) => [{ participantId, caseId: 'C2', minimumAcceptableNPV: [50000, 40000, 150000][index], maximumFundingExposure: [175000, 120000, 275000][index], thresholdOwnerId: participantId, status: synthetic }, { participantId, caseId: 'C3', minimumAcceptableNPV: 0, maximumFundingExposure: [175000, 120000, 275000][index], thresholdOwnerId: participantId, status: synthetic }]), participantEconomicCases: ['C2', 'C3'].flatMap(caseId => members.map((participantId, index) => ({ participantId, caseId, memberNPV: economicCases[caseId].memberNPVs[index], fundingExposure: [150000, 100000, 250000][index], status: synthetic }))), distributionRules: ['C2', 'C3'].flatMap(caseId => members.map(participantId => ({ caseId, participantId, benefitShare: 1 / 3, operatingCostShare: 1 / 3, investmentShare: 1 / 3, riskCostShare: 1 / 3, acceptanceStatus: 'Unresolved', status: synthetic }))) });
  const c2 = scenarioComparison(workspace, 'C2'); const c3 = scenarioComparison(workspace, 'C3');
  assert.equal(c2.attribution, 'FEDERATION_INCREMENT'); assert.equal(c3.attribution, 'BOUNDED_AI_INCREMENT'); assert.equal(classifyEconomicAttribution(c3.selectedCase, c2.comparatorCase), 'UNRESOLVED');
  assert.equal(c2.incrementalEconomics.riskAdjusted, 289200); assert.equal(c3.incrementalEconomics.riskAdjusted, 83780); assert.equal(economicCases.C2.collectiveNPV, 770525.48); assert.equal(economicCases.C3.collectiveNPV, 193580.99);
  const viableC2 = evaluateRequiredMemberViability(workspace.participants, workspace.participantEconomicCases, workspace.memberEconomicThresholds, members, 'C2'); assert.equal(viableC2.overallResult, 'PASS');
  const stressed = evaluateRequiredMemberViability(workspace.participants, workspace.participantEconomicCases.map(item => item.caseId === 'C2' && item.participantId === 'PAR-MERIDIAN' ? { ...item, memberNPV: 25000 } : item), workspace.memberEconomicThresholds, members, 'C2'); assert.equal(stressed.overallResult, 'FAIL'); assert.deepEqual(stressed.failingParticipantIds, ['PAR-MERIDIAN']);
  assert.equal(validateDistributionRules('C2', workspace.distributionRules, ['benefit', 'operatingCost', 'investment', 'riskCost']).valid, true);

  const admissions = members.map((participantId, index) => ({ id: `MEM-${index}`, participantId, eventType: 'ADMITTED', decisionId: `DEC-ADM-${index}`, effectiveTime: '2027-01-01T00:00:00Z', acceptedByParty: true, status: synthetic }));
  assert.equal(validateDependencyMembershipSeparation({ id: 'DEP-INTEROP', providerParticipantId: 'PAR-INTEROP', sponsorMemberId: 'PAR-MERIDIAN', dependencyType: 'Shared Interoperability Service' }, admissions, '2027-01-02T00:00:00Z').providerMembership, 'non-member');
  assert.equal(normalizePermission(permission).createsAuthority, false);
  const commitment = { id: 'COM-COORD', workId: 'WORK-COORDINATION', owningMemberId: 'PAR-HARBOR', requestEventId: 'REQ-1', offerEventId: 'OFF-1', acceptanceEventId: 'ACC-1', authorityEnvelopeId: authority.id, permissionId: permission.id, state: 'ACCEPTED', effectiveTime: '2027-01-02T00:00:00Z', status: synthetic };
  assert.equal(validateCommitmentState(commitment, [{ id: 'ACC-1' }]).valid, true); assert.equal(validateExecutionAgainstCommitment({ id: 'EX-1', commitmentId: commitment.id, completionClaimed: false }, commitment).completionAdvanced, false);
  assert.equal(normalizeEvidenceLineage({ id: 'EL-2', externalEvidenceId: 'EVD-REF', version: '2', effectiveTime: '2027-01-03T00:00:00Z', supersedesId: 'EL-1', correctionReason: 'Correction', status: synthetic }).supersedesId, 'EL-1');
  const lifecycle = [{ id: 'LC-1', objectId: commitment.id, effectiveTime: '2027-01-01T00:00:00Z', stateAfter: 'REQUESTED' }, { id: 'LC-2', objectId: commitment.id, effectiveTime: '2027-01-02T00:00:00Z', stateAfter: 'ACCEPTED' }, { id: 'LC-3', objectId: commitment.id, effectiveTime: '2027-02-01T00:00:00Z', stateAfter: 'CANCELLED' }];
  assert.equal(validateAsOfReconstruction({ lifecycleEvents: lifecycle }, 'lifecycle', commitment.id, '2027-01-02T12:00:00Z').reconstructedState, 'ACCEPTED'); assert.equal(validateAsOfReconstruction({ lifecycleEvents: [...lifecycle].reverse() }, 'lifecycle', commitment.id, '2027-01-02T12:00:00Z').reconstructedState, 'ACCEPTED');

  const releaseInput = { capability, baseline, fallback, inputBoundaries: [input], outputBoundaries: [output], authorityCrosswalks: [crosswalk], evaluations: [{ aiCapabilityId: capability.id, version: capability.version, evaluationQuestion: 'Top-3 recall', metric: 'top-3 recall', acceptanceRule: '>=95', observedResult: 97, status: synthetic }], abstentionRules: [{ aiCapabilityId: capability.id, triggerCondition: 'mandatory input missing or invalid', detectionMethod: 'input validation', requiredResponse: 'Use FBP-RANK', prohibitedResponse: 'Do not rank', fallbackId: fallback.id, testResult: '100% synthetic abstention on mandatory-invalid/missing cases', status: synthetic }], monitoringTriggers: [{ aiCapabilityId: capability.id, aiCapabilityVersion: capability.version, measure: 'material constraint violations', sourceId: 'SYS-AUDIT', frequency: 'per review', threshold: '>=1', observationOwnerId: 'ROLE-OBSERVER', reviewOwnerId: 'ROLE-REVIEWER', immediateResponse: 'Route to accountable review', decisionSLA: '4 hours', status: synthetic }], releaseCriteria: [{ aiCapabilityId: capability.id, criterionType: 'No autonomous action', requiredState: 'PASS', observedState: 'PASS', status: synthetic }], authorityEnvelope: authority, permission, commitment, asOfTime: '2027-01-16T00:00:00Z' };
  const ready = evaluateBoundedRelease(releaseInput); assert.equal(ready.status, 'READY_FOR_BOUNDED_RELEASE_DECISION'); assert.equal(ready.releaseAllowed, false); assert.equal(ready.autonomousActivation, false); assert.equal(evaluateBoundedRelease({ ...releaseInput, accountableDecision: releaseDecision }).releaseAllowed, true);
  assert.equal(evaluateAbstention(releaseInput.abstentionRules[0], { mandatoryInputMissing: true }), 'ABSTAIN'); assert.equal(validateAIOutputBoundary(output).createsCommitment, false);
  const suspension = { id: 'SUS-RANK', aiCapabilityId: capability.id, aiCapabilityVersion: capability.version, decisionId: 'DEC-SUS', authorityId: authority.id, effectiveTime: '2027-02-01T00:00:00Z', newUseBlocked: true, historicalOutputsPreserved: true, fallbackId: fallback.id, status: synthetic };
  assert.equal(validateAISuspension(suspension, { id: 'DEC-SUS', decisionOwnerId: 'PAR-HARBOR' }, authority, fallback, '2027-02-02T00:00:00Z').overallStatus, 'PASS');
  const recovery = { id: 'RCV-RANK', aiCapabilityId: capability.id, aiCapabilityVersion: capability.version, suspensionId: suspension.id, status: synthetic }; const gates = ['TECHNICAL', 'AUTHORITY_ACCEPTANCE', 'PERSON_CENTERED'].map((gateType, index) => ({ id: `G-${index}`, recoveryCaseId: recovery.id, gateType, finding: 'SATISFIED', reviewerId: 'PAR-HARBOR', reviewTime: '2027-02-03T00:00:00Z', status: synthetic }));
  assert.equal(evaluateRecoveryCase(recovery, gates).overall, 'PASS_FOR_REACTIVATION_DECISION'); assert.equal(evaluateRecoveryCase(recovery, gates).autoReactivated, false); assert.equal(deriveAICapabilityLifecycleState({ capability, releaseDecisions: [releaseDecision], suspensions: [suspension] }, '2027-02-15T00:00:00Z').state, 'SUSPENDED');
});
